language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - sys-img-armeabi-android-10

jdk:
  - oraclejdk8

install:
  - ./gradlew clean assemble

before_script:
  - echo no | android create avd --force -n test -t android-10 --abi armeabi
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  # JavaVM tests
  - ./gradlew --continue check
  # Android tests
  - ./gradlew conCheck

after_success:
  - gradle/deploy_snapshot.sh

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
