language: android

android:
  components:
  - build-tools-22.0.1
  - android-22
  - extra-android-m2repository
  - sys-img-armeabi-android-10

jdk:
  - oraclejdk8

install:
  - ./gradlew clean assemble

before_script:
  - echo no | android create avd --force -n test -t android-10 --abi armeabi
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - ./gradlew --continue check
  - ./gradlew conCheck

after_success:
  - gradle/deploy_snapshot.sh

notifications:
  email: false

sudo: false

cache:
  directories:
  - "$HOME/.gradle"

env:
  global:
  - secure: JbMPRX0sOLSIkiF02ZpCI9fW72+d2T1rZ1+kBPv8yh2hC8/5nEQwd6SI9H63P3yXlm7L8gb80RG95kGjDidYFdxKjdFkP9cdxmXNpxo2AwhhR3VSo7oqZtFw+lsdfwoNefmS01a4l3oAl7lpwAxRYgewTskwkC2wgXCteDBlh1eJN9B5oMJ2QDRlod96Ko6LnYd1RCPfYuioLYJjNqWKeeTjAIeGQtrKgZS2Sgwfe0qApd3a0mZXMEf26gErzHwTojvxlccMo2oLgdEs6W10rDd7WE/H24vtPq3L3TSHcJajdxIc+4Omfqi9RrsKoE7Zw3ql1STKQH9liLgYZMeaxpHP+j0k3PFyuSm8yMbDLALiINQP/3hV9+v4FiZOguIjmsngenjlZJX3fIIjVInTFhwFVuHKixV0hphavjxMKXm+lrk8qZT42fTLkzqiqtAAcCkDbLKW8vQUNopw7aK+g96m0oizOUo5wf3GPA3+oODeBn8AYP951PJ3+HZjcSHjp6JBL393z5QuGAnjnzMORu5lswCtjS4hwUChwYY9uipPkZ80JA8DXe/cbwzagV1djc5T9E7HNw8I/dUagg7JPcKwXKkR1oGVkuXUHoXJfA0a/PWXeE++9x/PEac/YeLKbbDTCSlPBcdnyGvIGhBo0i6/KXoLrVCxx07BnKWrWhw=
  - secure: kWILoYMHLIePyyxGPQeZu9NzyPtCYAMonJV2wMosU3Lj1Cw9d+waohBjcQC/TF1eUJ8aeq6SzW0+m63jZKt5kBZx2gz8KkNGiI23/l7mfDKsLkYqxvaLMf7pIFItLrhe4NYuky59l8c74PX1Vvz4I1WJD0cZq3T2Bk4UPOnDNG/GDR79pmAXFGDWKxtMkq0vhXpNAK19K0hzfD8jH4BuyrTNA62q09u/p//X0Z1HXI9rKmZEJjYEm5lgZIXCTov72V60Fym6lYl1qYYiJv7xwFVivLY65PstPw7U+b8Q8HkuJKQZDsFEhXcSHnNjlKlk3So3Wshiu4vqNne+KBWmn8PDg7Cxfls9SGFSBHhNcWbByb8Jpy5ksEabRY9bR1aYJz0FcgnERgdBY+7rao64oRaBJ48TJHx2Js91BVZSB9dHGmq31NIHnCvQ1D/g/+R5fD40jhaPnhj+KujMiheqa+XLfJ+/fr3hcXqr5Z/jZ4y7mjvZRJcm6fbCwIYiaJ0Htl4b8wMqR/YtAVA9Vx2yI9aLj4L27hqAu5QfMD2mA+vYQFOOfb0XpSNz2Lz2QPuyApNe955X/U4u3/ZtmCVC/uywDntEC4sLji04ISxD47row0z/sovxjYETfkxuyVuQJHjUL097GTLemcSlD1zoDO5IOYVerbmLKv0BerstPjw=
